# Common application configuration
spring:
  application:
    name: ecommerce

  # Database
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_db
    username: postgres
    password: admin123
    driver-class-name: org.postgresql.Driver
    hikari:
      initialization-fail-timeout: 0
      connection-timeout: 30000
      maximum-pool-size: 10

  # JPA
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false

  # Flyway
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: true
    repair-on-migration: true

  # Security
  security:
    user:
      name: admin
      password: ${ADMIN_PASSWORD:admin}

# Application specific configuration
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
      expiration: 86400000 # 1 day in milliseconds

# Logging
logging:
  level:
    root: INFO
    io.github.leupesquisa.ecommerce: INFO
    org.springframework: WARN
    org.hibernate: WARN

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

# Server
server:
  port: 8080
  error:
    include-stacktrace: never
    include-message: never

# Springdoc OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  packages-to-scan: io.github.leupesquisa.ecommerce
