# Development profile configuration
spring:
  # Database
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_db
    username: postgres
    password: admin123
    hikari:
      maximum-pool-size: 5
  
  # JPA
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  # Flyway
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: false  # Allow database cleaning in dev (CAUTION!)

# Logging
logging:
  level:
    io.github.leupesquisa.ecommerce: DEBUG
    org.springframework: INFO
    org.springframework.boot.autoconfigure.jdbc: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,flyway,loggers
  endpoint:
    health:
      show-details: always

# Server
server:
  port: 8080
  error:
    include-stacktrace: always
    include-message: always